// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hotel.DDD.Infraestructura;

#nullable disable

namespace hotel.DDD.Infraestructura.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20230314201428_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("hotel.DDD.Dominio.Generico.EventoGuardado", b =>
                {
                    b.Property<int>("IdGuardado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGuardado"));

                    b.Property<string>("CuerpoDelEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdAgregado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreGuardado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdGuardado");

                    b.ToTable("EventoGuardado", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
